spring:
  application:
    name: consumer-order
server:
  port: 8080
ruott:
  rpc:
    server-name: ${spring.application.name}
    host: 127.0.0.1
    port: 28000
    serializer: jdk
    retry-config:
      strategy: 'fixedTimeRetry'
    registry-config:
      registrar: 'etcd'
      address: http://127.0.0.1:2379
